import type { Partner } from '@/types/partners.types'

export const mockPartnersApplicants: Partner[] = [
  {
    id: 'partner1',
    name: 'ChefTools Pro',
    type: 'equipment',
    description: 'Производитель профессионального кухонного инвентаря и экипировки для поваров. Широкий ассортимент ножей, посуды и аксессуаров премиум-класса.',
    benefits: [
      'Скидка 15% на весь ассортимент для пользователей ChefUp',
      'Бесплатная доставка при заказе от 20 000 ₸',
      'Эксклюзивные мастер-классы по уходу за инструментами',
    ],
    website: 'https://cheftools.pro',
    contactEmail: 'info@cheftools.pro',
    contactPhone: '+7 (777) 123-45-67',
    targetAudience: ['applicant'],
    logoUrl: '',
    imageUrl: '',
  },
  {
    id: 'partner2',
    name: 'Академия поваров "Мастер"',
    type: 'education',
    description: 'Профессиональная школа поваров с 10-летним опытом. Курсы от базового до продвинутого уровня, сертификация, стажировки в ресторанах-партнёрах.',
    benefits: [
      'Скидка 20% на все курсы для пользователей ChefUp',
      'Бесплатное пробное занятие',
      'Гарантированное трудоустройство после окончания',
    ],
    website: 'https://academy-master.kz',
    contactEmail: 'info@academy-master.kz',
    contactPhone: '+7 (727) 234-56-78',
    targetAudience: ['applicant'],
    logoUrl: '',
    imageUrl: '',
  },
  {
    id: 'partner3',
    name: 'ChefWear',
    type: 'clothing',
    description: 'Бренд профессиональной одежды для кухни. Удобные, стильные и функциональные формы для поваров всех уровней.',
    benefits: [
      'Скидка 10% на первую покупку',
      'Бесплатная персонализация (вышивка имени)',
      'Программа лояльности с накопительными бонусами',
    ],
    website: 'https://chefwear.kz',
    contactEmail: 'sales@chefwear.kz',
    targetAudience: ['applicant'],
    logoUrl: '',
    imageUrl: '',
  },
  {
    id: 'partner4',
    name: 'Fresh Ingredients Co.',
    type: 'ingredients',
    description: 'Поставщик премиальных ингредиентов для ресторанов и частных поваров. Прямые поставки от производителей, гарантия качества.',
    benefits: [
      'Специальные цены для пользователей ChefUp',
      'Доставка в день заказа',
      'Консультации по выбору ингредиентов',
    ],
    website: 'https://fresh-ingredients.kz',
    contactEmail: 'orders@fresh-ingredients.kz',
    contactPhone: '+7 (727) 345-67-89',
    targetAudience: ['applicant'],
    logoUrl: '',
    imageUrl: '',
  },
  {
    id: 'partner5',
    name: 'Ресторан "Гастроном"',
    type: 'internships',
    description: 'Премиальный ресторан, предлагающий стажировки для начинающих поваров. Работа под руководством опытных шеф-поваров.',
    benefits: [
      'Приоритетное рассмотрение заявок от пользователей ChefUp',
      'Оплачиваемая стажировка',
      'Возможность трудоустройства после стажировки',
    ],
    website: 'https://gastronom.kz',
    contactEmail: 'careers@gastronom.kz',
    targetAudience: ['applicant'],
    logoUrl: '',
    imageUrl: '',
  },
]

export const mockPartnersEmployers: Partner[] = [
  {
    id: 'partner6',
    name: 'Restaurant Equipment Solutions',
    type: 'restaurant-equipment',
    description: 'Поставщик профессионального оборудования для ресторанов. Полный спектр техники от ведущих мировых производителей.',
    benefits: [
      'Скидка 5% на оборудование для ресторанов-партнёров ChefUp',
      'Бесплатная консультация и проектирование кухни',
      'Гарантийное и постгарантийное обслуживание',
    ],
    website: 'https://restaurant-equipment.kz',
    contactEmail: 'sales@restaurant-equipment.kz',
    contactPhone: '+7 (727) 456-78-90',
    targetAudience: ['employer'],
    offers: [
      'Лизинг оборудования',
      'Trade-in старого оборудования',
      'Монтаж и пусконаладка',
    ],
    conditions: 'Минимальный заказ 500 000 ₸. Рассрочка до 24 месяцев.',
    logoUrl: '',
    imageUrl: '',
  },
  {
    id: 'partner7',
    name: 'HoReCa Supply Chain',
    type: 'raw-materials',
    description: 'Крупный поставщик сырья для HoReCa. Прямые контракты с производителями, стабильные цены, гарантия качества.',
    benefits: [
      'Специальные условия для ресторанов-партнёров ChefUp',
      'Ежедневная доставка',
      'Гибкая система оплаты',
    ],
    website: 'https://horeca-supply.kz',
    contactEmail: 'info@horeca-supply.kz',
    contactPhone: '+7 (727) 567-89-01',
    targetAudience: ['employer'],
    offers: [
      'Индивидуальные условия поставки',
      'Консультации по меню и закупкам',
      'Программа лояльности',
    ],
    conditions: 'Минимальный заказ 100 000 ₸ в месяц.',
    logoUrl: '',
    imageUrl: '',
  },
  {
    id: 'partner8',
    name: 'Restaurant Accounting Pro',
    type: 'accounting',
    description: 'Бухгалтерский сервис, специализирующийся на ресторанном бизнесе. Ведение учёта, налоговая отчётность, консультации.',
    benefits: [
      'Скидка 20% на первый месяц обслуживания',
      'Бесплатная консультация по налогообложению',
      'Интеграция с популярными POS-системами',
    ],
    website: 'https://restaurant-accounting.kz',
    contactEmail: 'info@restaurant-accounting.kz',
    contactPhone: '+7 (727) 678-90-12',
    targetAudience: ['employer'],
    offers: [
      'Ведение бухгалтерского учёта',
      'Налоговая отчётность',
      'Консультации по оптимизации налогов',
    ],
    conditions: 'От 15 000 ₸ в месяц. Первый месяц со скидкой.',
    logoUrl: '',
    imageUrl: '',
  },
  {
    id: 'partner9',
    name: 'RestaurantTech',
    type: 'automation',
    description: 'Сервисы автоматизации ресторанного бизнеса. POS-системы, онлайн-заказы, CRM, аналитика.',
    benefits: [
      'Скидка 15% на установку и настройку',
      'Бесплатное обучение персонала',
      'Техническая поддержка 24/7',
    ],
    website: 'https://restaurant-tech.kz',
    contactEmail: 'sales@restaurant-tech.kz',
    contactPhone: '+7 (727) 789-01-23',
    targetAudience: ['employer'],
    offers: [
      'POS-системы',
      'Онлайн-заказы и доставка',
      'CRM для ресторанов',
      'Аналитика и отчёты',
    ],
    conditions: 'Аренда от 10 000 ₸/месяц или покупка с рассрочкой.',
    logoUrl: '',
    imageUrl: '',
  },
  {
    id: 'partner10',
    name: 'HoReCa Consulting Group',
    type: 'consulting',
    description: 'Консалтинговая группа, специализирующаяся на ресторанном бизнесе. Оптимизация процессов, управление персоналом, маркетинг.',
    benefits: [
      'Бесплатная первичная консультация',
      'Скидка 10% на все услуги для партнёров ChefUp',
      'Индивидуальный подход к каждому проекту',
    ],
    website: 'https://horeca-consulting.kz',
    contactEmail: 'info@horeca-consulting.kz',
    contactPhone: '+7 (727) 890-12-34',
    targetAudience: ['employer'],
    offers: [
      'Оптимизация бизнес-процессов',
      'Управление персоналом',
      'Маркетинг и продвижение',
      'Финансовое планирование',
    ],
    conditions: 'Индивидуальные условия в зависимости от проекта.',
    logoUrl: '',
    imageUrl: '',
  },
]

