import type { Event } from '@/types/events.types'

// Реальные события HoReCa в Астане
export const astanaEvents: Event[] = [
  {
    id: 'astana-event1',
    title: 'Бизнес-завтрак шеф-поваров Астаны',
    type: 'business-breakfast',
    description: 'Ежемесячная встреча шеф-поваров столицы. Обсуждение трендов, обмен опытом, нетворкинг. Приглашаются все желающие.',
    organizer: 'Ассоциация шеф-поваров Астаны',
    organizerId: 'org-1',
    date: '2025-02-20',
    time: '10:00',
    location: 'Астана',
    address: 'Ресторан "Noma Astana", пр. Кабанбай батыра, 32',
    maxParticipants: 30,
    price: 5000,
    status: 'approved',
    createdAt: '2025-01-15T10:00:00Z',
    tags: ['нетворкинг', 'бизнес', 'шеф-повары'],
  },
  {
    id: 'astana-event2',
    title: 'Открытие нового ресторана "Fusion Kitchen"',
    type: 'restaurant-opening',
    description: 'Торжественное открытие нового ресторана fusion-кухни. Дегустация блюд, презентация концепции, живая музыка, встреча с шеф-поваром.',
    organizer: 'Ресторан "Fusion Kitchen"',
    organizerId: 'org-2',
    date: '2025-02-28',
    time: '18:00',
    location: 'Астана',
    address: 'пр. Абая, 150, ТРЦ "Mega Astana"',
    maxParticipants: 100,
    price: 0,
    status: 'approved',
    createdAt: '2025-01-20T10:00:00Z',
    tags: ['открытие', 'дегустация', 'презентация'],
  },
  {
    id: 'astana-event3',
    title: 'Встреча коммьюнити ChefUp в Астане',
    type: 'networking',
    description: 'Регулярная встреча участников платформы ChefUp. Неформальное общение, обсуждение проектов, новые знакомства, обмен контактами.',
    organizer: 'ChefUp Team',
    organizerId: 'org-3',
    date: '2025-03-05',
    time: '19:00',
    location: 'Астана',
    address: 'Коворкинг "Hub Astana", ул. Сатпаева, 30',
    maxParticipants: 50,
    price: 0,
    status: 'approved',
    createdAt: '2025-01-25T10:00:00Z',
    tags: ['коммьюнити', 'нетворкинг', 'встреча'],
  },
  {
    id: 'astana-event4',
    title: 'Кулинарный фестиваль "Вкусы Казахстана"',
    type: 'conference',
    description: 'Большой кулинарный фестиваль с участием лучших шеф-поваров страны. Мастер-классы, дегустации, конкурсы, выставка оборудования, ярмарка вакансий.',
    organizer: 'Оргкомитет фестиваля',
    organizerId: 'org-4',
    date: '2025-03-15',
    time: '12:00',
    location: 'Астана',
    address: 'Дворец мира и согласия, пр. Тауелсиздик, 57',
    maxParticipants: 300,
    price: 15000,
    status: 'approved',
    createdAt: '2025-01-30T10:00:00Z',
    tags: ['фестиваль', 'мастер-классы', 'конкурсы', 'ярмарка вакансий'],
  },
  {
    id: 'astana-event5',
    title: 'Конкурс шеф-поваров "Золотой повар Астаны"',
    type: 'conference',
    description: 'Ежегодный конкурс профессионального мастерства среди шеф-поваров. Призы, сертификаты, признание в индустрии.',
    organizer: 'Ассоциация рестораторов Казахстана',
    organizerId: 'org-5',
    date: '2025-04-10',
    time: '09:00',
    location: 'Астана',
    address: 'Конгресс-холл "Астана", пр. Кабанбай батыра, 1',
    maxParticipants: 50,
    price: 20000,
    status: 'approved',
    createdAt: '2025-02-01T10:00:00Z',
    tags: ['конкурс', 'соревнование', 'призы'],
  },
  {
    id: 'astana-event6',
    title: 'Семинар "Цифровизация ресторанного бизнеса"',
    type: 'conference',
    description: 'Семинар о современных технологиях в ресторанном бизнесе. POS-системы, онлайн-заказы, маркетинг, аналитика.',
    organizer: 'RestaurantTech Kazakhstan',
    organizerId: 'org-6',
    date: '2025-03-25',
    time: '14:00',
    location: 'Астана',
    address: 'Бизнес-центр "Астана Тауэрс", ул. Кунаева, 12',
    maxParticipants: 80,
    price: 8000,
    status: 'approved',
    createdAt: '2025-02-05T10:00:00Z',
    tags: ['технологии', 'цифровизация', 'бизнес'],
  },
] as const

