import type { Event } from '@/types/events.types'

export const mockEvents: Event[] = [
  {
    id: 'event1',
    title: 'Бизнес-завтрак шеф-поваров',
    type: 'business-breakfast',
    description: 'Ежемесячная встреча шеф-поваров для обмена опытом и нетворкинга. Обсуждение трендов в индустрии HoReCa, новых технологий и подходов к управлению кухней.',
    organizer: 'ChefUp Community',
    organizerId: 'organizer1',
    date: '2025-02-20',
    time: '10:00',
    location: 'Алматы',
    address: 'Ресторан "Noma", ул. Абая, 150',
    maxParticipants: 25,
    price: 5000,
    status: 'approved',
    createdAt: '2025-01-15T10:00:00Z',
    tags: ['нетворкинг', 'бизнес', 'шеф-повары'],
  },
  {
    id: 'event2',
    title: 'Открытие нового ресторана "Fusion"',
    type: 'restaurant-opening',
    description: 'Приглашаем на открытие нового ресторана с участием топ-шефов региона. Дегустация блюд, презентация концепции, живая музыка.',
    organizer: 'Ресторан "Fusion"',
    organizerId: 'organizer2',
    date: '2025-02-28',
    time: '18:00',
    location: 'Астана',
    address: 'ул. Абая, 150',
    maxParticipants: 50,
    price: 0,
    status: 'approved',
    createdAt: '2025-01-20T10:00:00Z',
    tags: ['открытие', 'дегустация', 'презентация'],
  },
  {
    id: 'event3',
    title: 'Встреча коммьюнити ChefUp',
    type: 'networking',
    description: 'Регулярная встреча участников платформы ChefUp для общения и обмена опытом. Неформальное общение, обсуждение проектов, новые знакомства.',
    organizer: 'ChefUp Team',
    organizerId: 'organizer3',
    date: '2025-03-05',
    time: '19:00',
    location: 'Алматы',
    address: 'Коворкинг "Hub", ул. Сатпаева, 30',
    maxParticipants: 40,
    price: 0,
    status: 'approved',
    createdAt: '2025-01-25T10:00:00Z',
    tags: ['коммьюнити', 'нетворкинг', 'встреча'],
  },
  {
    id: 'event4',
    title: 'Кулинарный фестиваль "Вкусы Центральной Азии"',
    type: 'conference',
    description: 'Большой кулинарный фестиваль с участием лучших шеф-поваров региона. Мастер-классы, дегустации, конкурсы, выставка оборудования.',
    organizer: 'Оргкомитет фестиваля',
    organizerId: 'organizer4',
    date: '2025-03-15',
    time: '12:00',
    location: 'Ташкент',
    address: 'Парк культуры и отдыха',
    maxParticipants: 200,
    price: 10000,
    status: 'approved',
    createdAt: '2025-01-30T10:00:00Z',
    tags: ['фестиваль', 'мастер-классы', 'конкурсы'],
  },
] as const

