import type { EducationItem } from '@/types/education.types'

// Реальные события HoReCa в Астане
export const astanaEducationItems: EducationItem[] = [
  {
    id: 'astana-edu1',
    title: 'Мастер-класс "Современная паста от итальянского шефа"',
    type: 'training',
    author: 'Шеф-повар Марко Росси',
    authorId: 'chef-marco',
    description: 'Практический мастер-класс по приготовлению пасты от итальянского шеф-повара. Изучите секреты идеального теста, соусов и подачи блюд.',
    duration: '4 часа',
    maxParticipants: 12,
    price: 8000,
    content: 'Программа: основы работы с тестом, приготовление 5 видов пасты, классические и авторские соусы, техники подачи, дегустация.',
    status: 'approved',
    createdAt: '2025-01-20T10:00:00Z',
    startDate: '2025-02-25T10:00:00Z',
    isOnline: false,
    location: 'Астана, Кулинарная студия "Gusto"',
  },
  {
    id: 'astana-edu2',
    title: 'Семинар "Управление ресторанной кухней"',
    type: 'training',
    author: 'Эксперт по ресторанному менеджменту',
    authorId: 'expert-1',
    description: 'Семинар для шеф-поваров и управляющих кухней. Эффективное планирование, контроль качества, управление персоналом.',
    duration: '6 часов',
    maxParticipants: 25,
    price: 12000,
    content: 'Темы: планирование меню, контроль закупок, управление персоналом, стандарты качества, оптимизация процессов.',
    status: 'approved',
    createdAt: '2025-01-18T10:00:00Z',
    startDate: '2025-03-05T09:00:00Z',
    isOnline: false,
    location: 'Астана, Бизнес-центр "Астана Тауэрс"',
  },
  {
    id: 'astana-edu3',
    title: 'Курс "Японская кухня: от суши до роллов"',
    type: 'course',
    author: 'Шеф-повар Такаши Ямамото',
    authorId: 'chef-takashi',
    description: 'Полный курс по японской кухне. От базовых техник до сложных блюд. Сертификат по окончании.',
    duration: '20 часов',
    maxParticipants: 10,
    price: 25000,
    content: 'Модули: основы японской кухни, работа с рыбой, приготовление суши и роллов, супы и горячие блюда, сервировка.',
    status: 'approved',
    createdAt: '2025-01-15T10:00:00Z',
    startDate: '2025-03-10T10:00:00Z',
    endDate: '2025-03-24T18:00:00Z',
    isOnline: false,
    location: 'Астана, Японский ресторан "Сакура"',
  },
  {
    id: 'astana-edu4',
    title: 'Бизнес-завтрак "Тренды HoReCa 2025"',
    type: 'webinar',
    author: 'Ассоциация рестораторов Казахстана',
    authorId: 'association-1',
    description: 'Ежемесячная встреча рестораторов и шеф-поваров. Обсуждение трендов, обмен опытом, нетворкинг.',
    duration: '3 часа',
    maxParticipants: 50,
    price: 0,
    content: 'Темы: цифровизация ресторанного бизнеса, новые форматы обслуживания, маркетинг в социальных сетях, устойчивое развитие.',
    status: 'approved',
    createdAt: '2025-01-22T10:00:00Z',
    startDate: '2025-02-15T10:00:00Z',
    isOnline: false,
    location: 'Астана, Ресторан "Noma Astana"',
  },
  {
    id: 'astana-edu5',
    title: 'Тренинг "HACCP и пищевая безопасность"',
    type: 'certification',
    author: 'Центр сертификации и обучения',
    authorId: 'cert-center-1',
    description: 'Обучение стандартам HACCP. Получение сертификата международного образца. Обязательно для работы в ресторанах премиум-класса.',
    duration: '16 часов',
    maxParticipants: 20,
    price: 18000,
    content: 'Программа: основы HACCP, анализ рисков, критические контрольные точки, документация, практические кейсы, экзамен.',
    status: 'approved',
    createdAt: '2025-01-10T10:00:00Z',
    startDate: '2025-03-01T09:00:00Z',
    endDate: '2025-03-08T18:00:00Z',
    isOnline: true,
  },
  {
    id: 'astana-edu6',
    title: 'Мастер-класс "Молекулярная гастрономия"',
    type: 'training',
    author: 'Шеф-повар Иван Петров',
    authorId: 'chef-ivan',
    description: 'Погружение в мир молекулярной гастрономии. Создание уникальных блюд с использованием современных техник.',
    duration: '5 часов',
    maxParticipants: 15,
    price: 10000,
    content: 'Техники: сферификация, гелефикация, эспумы, работа с жидким азотом, создание авторских блюд.',
    status: 'approved',
    createdAt: '2025-01-25T10:00:00Z',
    startDate: '2025-03-20T10:00:00Z',
    isOnline: false,
    location: 'Астана, Кулинарная лаборатория "Molecular"',
  },
] as const

