import type { EducationItem } from '@/types/education.types'

export const mockEducationItems: EducationItem[] = [
  {
    id: 'edu1',
    title: 'Мастер-класс по молекулярной кухне',
    type: 'training',
    author: 'Шеф-повар Иван Петров',
    authorId: 'author1',
    description: 'Изучите основы молекулярной гастрономии и создайте уникальные блюда. Практический мастер-класс с демонстрацией техник и дегустацией.',
    duration: '4 часа',
    maxParticipants: 15,
    price: 5000,
    content: 'Программа мастер-класса включает: введение в молекулярную гастрономию, работа с жидким азотом, создание сфер, пены и гелей, практические упражнения, дегустация блюд.',
    videoUrl: '',
    materials: [],
    status: 'approved',
    createdAt: '2025-01-10T10:00:00Z',
    startDate: '2025-02-15T10:00:00Z',
    isOnline: false,
    location: 'Алматы, Кулинарная студия "Гастроном"',
  },
  {
    id: 'edu2',
    title: 'Курс "Управление кухней ресторана"',
    type: 'course',
    author: 'Эксперт Мария Сидорова',
    authorId: 'author2',
    description: 'Освойте навыки эффективного управления персоналом и оптимизации процессов на кухне. Комплексный курс для шеф-поваров и управляющих.',
    duration: '16 часов',
    maxParticipants: 20,
    price: 15000,
    content: 'Курс включает модули: планирование меню и закупок, управление персоналом, контроль качества, оптимизация процессов, финансовое планирование, работа с поставщиками.',
    videoUrl: '',
    materials: ['https://example.com/materials/management.pdf'],
    status: 'approved',
    createdAt: '2025-01-08T10:00:00Z',
    startDate: '2025-02-20T09:00:00Z',
    endDate: '2025-03-20T18:00:00Z',
    isOnline: true,
  },
  {
    id: 'edu3',
    title: 'Сертификация HACCP',
    type: 'certification',
    author: 'Международный центр сертификации',
    authorId: 'author3',
    description: 'Получите международный сертификат по пищевой безопасности HACCP. Обязательно для работы в ресторанах премиум-класса.',
    duration: '24 часа',
    maxParticipants: 30,
    price: 20000,
    content: 'Программа сертификации: основы HACCP, анализ рисков, критические контрольные точки, документация, практические кейсы, экзамен.',
    videoUrl: '',
    materials: ['https://example.com/materials/haccp-guide.pdf'],
    status: 'approved',
    createdAt: '2025-01-05T10:00:00Z',
    startDate: '2025-03-01T09:00:00Z',
    endDate: '2025-03-15T18:00:00Z',
    isOnline: true,
  },
  {
    id: 'edu4',
    title: 'Вебинар "Тренды в HoReCa 2025"',
    type: 'webinar',
    author: 'Аналитик Алексей Козлов',
    authorId: 'author4',
    description: 'Узнайте о последних трендах в индустрии HoReCa, новых технологиях и подходах к управлению ресторанами.',
    duration: '2 часа',
    maxParticipants: 100,
    price: 0,
    content: 'Темы вебинара: цифровизация ресторанного бизнеса, устойчивое развитие, новые форматы обслуживания, маркетинг в социальных сетях.',
    videoUrl: 'https://youtube.com/watch?v=example',
    materials: [],
    status: 'approved',
    createdAt: '2025-01-12T10:00:00Z',
    startDate: '2025-02-10T15:00:00Z',
    isOnline: true,
  },
  {
    id: 'edu5',
    title: 'Тренинг по японской кухне',
    type: 'training',
    author: 'Шеф-повар Такаши Ямамото',
    authorId: 'author5',
    description: 'Практический тренинг по приготовлению традиционных японских блюд: суши, сашими, рамен, темпура.',
    duration: '6 часов',
    maxParticipants: 12,
    price: 8000,
    content: 'Программа: основы японской кухни, работа с рыбой, приготовление риса для суши, техники нарезки, сервировка, дегустация.',
    videoUrl: '',
    materials: [],
    status: 'approved',
    createdAt: '2025-01-15T10:00:00Z',
    startDate: '2025-02-25T10:00:00Z',
    isOnline: false,
    location: 'Астана, Японский ресторан "Сакура"',
  },
] as const

